name: React CI with Docker

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t react-app .

      - name: Run container (optional test)
        run: docker run -d -p 3000:80 react-app
